// Generated by gencpp from file laser_go/AddInts.msg
// DO NOT EDIT!


#ifndef LASER_GO_MESSAGE_ADDINTS_H
#define LASER_GO_MESSAGE_ADDINTS_H

#include <ros/service_traits.h>


#include <laser_go/AddIntsRequest.h>
#include <laser_go/AddIntsResponse.h>


namespace laser_go
{

struct AddInts
{

typedef AddIntsRequest Request;
typedef AddIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddInts
} // namespace laser_go


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::laser_go::AddInts > {
  static const char* value()
  {
    return "4781436a0c2affec8025955a6041e481";
  }

  static const char* value(const ::laser_go::AddInts&) { return value(); }
};

template<>
struct DataType< ::laser_go::AddInts > {
  static const char* value()
  {
    return "laser_go/AddInts";
  }

  static const char* value(const ::laser_go::AddInts&) { return value(); }
};


// service_traits::MD5Sum< ::laser_go::AddIntsRequest> should match
// service_traits::MD5Sum< ::laser_go::AddInts >
template<>
struct MD5Sum< ::laser_go::AddIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::laser_go::AddInts >::value();
  }
  static const char* value(const ::laser_go::AddIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::laser_go::AddIntsRequest> should match
// service_traits::DataType< ::laser_go::AddInts >
template<>
struct DataType< ::laser_go::AddIntsRequest>
{
  static const char* value()
  {
    return DataType< ::laser_go::AddInts >::value();
  }
  static const char* value(const ::laser_go::AddIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::laser_go::AddIntsResponse> should match
// service_traits::MD5Sum< ::laser_go::AddInts >
template<>
struct MD5Sum< ::laser_go::AddIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::laser_go::AddInts >::value();
  }
  static const char* value(const ::laser_go::AddIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::laser_go::AddIntsResponse> should match
// service_traits::DataType< ::laser_go::AddInts >
template<>
struct DataType< ::laser_go::AddIntsResponse>
{
  static const char* value()
  {
    return DataType< ::laser_go::AddInts >::value();
  }
  static const char* value(const ::laser_go::AddIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LASER_GO_MESSAGE_ADDINTS_H
